version: "1"

services:
  frontend: 
    build: ./frontend
    ports:
      -"3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      -"5000:5000"
    depends_on:
      - database
  
  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/fatih/mongo-backup: /data/db
